name: blackthertins_flutter_lints
description: Recommended lints for my Flutter apps, packages and plugins
version: 1.0.0

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter_lints: ^2.0.1
